### ISSUE TITLE
Custom events for articles

### ISSUE THREAD

**Issue by tyssejc** [searchdiscovery/client-kenvue-ga4-dl-spec#25]
Related to #24 

We are looking to provide more in depth reporting for articles, specifically Article Cards and Article Lists.

I would suggest utilizing the existing generic `select_content` event and adding new generic events such as `view_content_list` and `view_content`, each with a `content_type` property which would have a value of `"article"`.

@StevenJRowe123 @jcottriel-sdi @jimalytics-sdi thoughts?

**Comment by jcottriel-further** [comment]
```
// Select Content from List
{
  event : select_content,
  content_type: "article",
  content_name: "This is an article",
  content_id: "abc123zyx987"
  content_list_type: "article"
  content_list_name: "feature articles",
  content_list_id: "123list987"
}
```

```

// View Content List
{
  event : view_content_list,
  content_type: "article",
  content_list_type: "article"
  content_list_name: "feature articles",
  content_list_id: "123list987"
}
```

```
// View Content
{
  event : view_content,
  content_type: "article",
  content_name: "This is an article",
  content_id: "abc123zyx987"
  content_list_type: "article"
  content_list_name: "feature articles",
  content_list_id: "123list987"
}
```

**Comment by tyssejc** [comment]
thanks @jcottriel-sdi!

what do we think about grouping content params under a parent param like `content_data`, similar to e.g. how we group ecommerce params under `ecommerce` and page data under `page_data`? that way we can clear content data if it changes but retain any other event or ecommerce data

**Comment by tyssejc** [comment]
for `view_content_list`, I'd think we'd need an array analogous to the `ecommerce.items` array if analysts wanted to know when content appeared in lists:

```js
// View Content List
{
  event : "view_content_list",
  content_data: {
    content_list_type: "article",
    content_list_name: "feature articles",
    content_list_id: "123list987",
    content: [
      {
        content_type: "article",
        content_name: "This is an article",
        content_id: "abc123zyx987"
      },
      {
        content_type: "article",
        content_name: "This is an article",
        content_id: "abc123zyx987"
      }
    ]
  }
}
```

GTM doesn't have a built-in way of parsing these, so we'd need to create e.g. a tag template to facilitate that.

(I'm starting to see why content-related events and params other than `select_content` were left out of the data model)

**Comment by jcottriel-further** [comment]
I think storing it under `event_data` would be good. I don't think we need to create a whole new object for it.

In regards to the array, just seems like a lot of work for no real benefit. Have we requested the business to provide us with a detailed business use case for this? What do they plan on reporting on? If they do report on this, what do they plan on doing with the information? Im hesitant to build out something so robust without any real plan to use it.

**Comment by tyssejc** [comment]
I'm with you — let's go with the events you suggested. We can regroup if the business has specific requirements.
